# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - run: |
           git fetch --prune --unshallow
           
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
 
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1
   

    - name: Restore NuGet packages
      #working-directory: D:\a\sonar_dotnet\sonar_dotnet\WebAnalysis
      run: nuget restore sonar-scanning-examples/sonarqube-scanner-msbuild/CSharpProject/SomeConsoleApplication.sln
      
    - name: add test logger package 
      run: dotnet add sonar-scanning-examples/sonarqube-scanner-msbuild/CSharpProject/SomeConsoleApplication.sln package NunitXml.TestLogger --version 3.0.107
      
    - name: test
      run: dotnet test sonar-scanning-examples/sonarqube-scanner-msbuild/CSharpProject/SomeConsoleApplication.sln --logger:"trx;LogFileName=testresult.xml
    
   
   
   
    - name: Upload a coverage Artifact dotcover
      uses: actions/upload-artifact@v2.2.4
      with:
        # Artifact name
        name: artifact 
        path: D:\a\sonar_dotnet\sonar_dotnet\.sonarqube\out\sonar-project.properties
